### ISSUE TITLE
GUI policy report display inconsistencies

### ISSUE THREAD

**Issue by epiil** [MediaArea/MediaConch#104]
I'm noticing the following GUI policy report display inconsistencies.Tested with daily build MediaConch_GUI_15.11.20151229_Mac.dmg

1. Check online file + MediaConchHtml display produces an XML Policy report. 
2. Check online file + MediaConchText display produces an XML Policy report. 
3. Check online file + MediaConchTextUnicode produces an XML Policy report. 

File used for testing was http://jell.yfish.us/media/Jellyfish-3-Mbps-1080p-h264.mkv

4. Check local folder + MediaConchHtml display produces both HTML and XML Policy reports. For example, testing /Users/erikpiil/MediaConch/Demo/files/ produces incorrect XML Policy reports for Testing_Multiple_Files_3.mkv and Standards_Mismatch.mkv (these are the first and fourth reports in the results queue for this particular batch). 

5. Check local folder + MediaConchText display produces both HTML and XML Policy reports. For example, testing /Users/erikpiil/MediaConch/Demo/files/ produces incorrect XML Policy reports for Testing_Multiple_Files_3.mkv and Standards_Mismatch.mkv (these are the first and fourth reports in the results queue for this particular batch). 

6. Check local folder + MediaConchTextUnicode display produces both HTML and XML Policy reports. For example, testing /Users/erikpiil/MediaConch/Demo/files/ produces incorrect XML Policy reports for Testing_Multiple_Files_3.mkv and Standards_Mismatch.mkv (these are the first and fourth reports in the results queue for this particular batch).

**Comment by tribouille** [comment]
Will be corrected in next release
