### ISSUE TITLE
Policies: "Field" value drops out when switching from Editor to Free text mode.

### ISSUE THREAD

**Issue by epiil** [MediaArea/MediaConch#107]
One *slight* bug I noticed in the GUI 15.12 build was that in when switching from Editor to Free text to Editor in the Policies tab, any filled-in data for Type, Field, Occurrence, Validator, and Value remain, while Field is erased. To reproduce:

1. Create New Rule
2. Populate Type, Field, Occurrence, Validator, Value
3. Switch to Free text
4. Switch back to Editor

**Comment by tribouille** [comment]
Resolved with https://github.com/MediaArea/MediaConch_SourceCode/pull/106
