### ISSUE TITLE
Minor docs issue - jumping to subsection - view obscured by header

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/MediaConch#110]
Hey, super minor issue but thought I'd report it anyhow.

The anchor tags (correct term?) are jumping to the right place but the fixed header isn't accounted for and obscures the view once you click.
 For example: 
https://mediaarea.net/MediaConch/documentation/HowToUse.html#field

**Comment by ablwr** [comment]
Kieran, thanks! I'm looking at other website issues now too so I will add this to the list.

**Comment by kieranjol** [comment]
:+1: :shell:

**Comment by kieranjol** [comment]
Looks great!
