### ISSUE TITLE
Modify documentation in readme and MediaConch webpage to reflect multi repos

### ISSUE THREAD

**Issue by ablwr** [MediaArea/MediaConch#113]
We recently spread out over many repos and this should be addressed so users know how to find the right place to be when perusing source code.

**Comment by JeromeMartinez** [comment]
should be on:
- Website
- README.md of MediaConch
- README.md of MediaConch_SourceCode

**Comment by ablwr** [comment]
@JeromeMartinez What about MediaInfoXml? Or should these three reference MediaInfoXml and that one should stay as-is because it is only a tangential relation?

**Comment by ablwr** [comment]
Resolved. Adding contributing.md to each will follow after internal screens.
