### ISSUE TITLE
Wish: More coherent end for no-parsing commands

### ISSUE THREAD

**Issue by retokromer** [MediaArea/MediaConch#114]
`mediaconch -v` and `mediaconch -h` give the information they are supposed to give, but end with an error flag. I suggest that also the no-parsing but correct commands exit with a true value.

**Comment by tribouille** [comment]
Done, will be in the next snapshots/release.
https://github.com/MediaArea/MediaConch_SourceCode/pull/124

**Comment by retokromer** [comment]
Thank you, @tribouille!

**Comment by tribouille** [comment]
As seen in https://github.com/MediaArea/MediaConch_SourceCode/issues/138, it should be solved.
