### ISSUE TITLE
libxslt dependency

### ISSUE THREAD

**Issue by retokromer** [MediaArea/MediaConch#119]
By using Linuxbrew on Ubuntu 14.04 LTS, you need to install `libxslt` before installing `mediaconch`. Then it works fine.

**Comment by JeromeMartinez** [comment]
@dericed, some [depends on](https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Formula/mediaconch.rb#L16-L19) are missing.

**Comment by JeromeMartinez** [comment]
@retokromer can it be considered as fixed now with Linuxbrew file update (done by you ;-) ) ?

**Comment by retokromer** [comment]
Yes, it works fine on my side. Thank you!

**Comment by JeromeMartinez** [comment]
> Thank you!

We did nothing, you did. So "thank you" is for yourself ;).
