### ISSUE TITLE
MediaConch GUI crashes when clicking any of the view buttons

### ISSUE THREAD

**Issue by Elorrain** [MediaArea/MediaConch#122]
I'm using MediaConch GUI Version 16.02 on OS X 10.6.8.
When I click any of the 'view report' buttons when the analyse of a file is completed, MediaConch crashes and quits. This is always the case no matter what kind of file format I check, including several FFV1/MKV files.
I don't have another computer around me right now, can it be linked to my OS version?
I attach the crash report.

[crash_report_10_6_8.zip](https://github.com/MediaArea/MediaConch/files/167960/crash_report_10_6_8.zip)

**Comment by tribouille** [comment]
Hi,

it should not related to the OS version.
Can you try to move your GUI database?
On Mac, you can find it in: ~/Library/Application Support/MediaConch/MediaConchUi.db.

Then, try a simple file (this one, without policy/display for instance : https://github.com/MediaArea/MediaConch_SampleFiles/raw/master/PolicyTestFiles/FFV1/ffv1_test_pixfmt-bgr0_coder-0_level-1.mkv). If you still have an error, put back the database.
If it works, maybe try to add a file (with the policy) you used.

If it works or not, you can put back the database, it should be enough to have some directions.

Thanks,
Florent.

**Comment by Elorrain** [comment]
Hi Florent,
I moved the MediaConchUi.db. away from the MediaConch folder and used your file. MediaConch was still crashing.
But one thing I've noticed is that with any file, if I click on the 'view' button of 'implementation' before the 'view' button of MediaInfo report, it doesn't crash. If I click on the MediaInfo report 'view' button directly after the analysis is done, it crashes. 
I've tested with and without the database file in the folder but it's always the same.
Also the MediaInfo report view window doesn't display anything (stays on loading…).

![mediaconch_capture](https://cloud.githubusercontent.com/assets/10517314/13703305/5666921a-e795-11e5-9633-972170db4bb8.png)


Thanks.

**Comment by tribouille** [comment]
Ok, thank you, I'll try to find out what is the problem.

Just to be sure, the file was finished to be analyzed? (the box on the right is green)
Does the Implementation report was displaying something when you clicked on it?

Last question, which package did you use?
(Homebrew, from https://mediaarea.net/MediaConch/downloads/mac_os.html, compiled, something else...)

Thanks.

**Comment by Elorrain** [comment]
Yes, the analyse was completed and the box was green. I attach a screenshot of the implementation report when I click on it:
![capture d ecran 2016-03-11 a 14 59 51](https://cloud.githubusercontent.com/assets/10517314/13704040/134c52a8-e79a-11e5-84d3-8e1464cfb961.png)

I got my version from https://mediaarea.net/MediaConch/downloads/mac_os.html
Thanks.

**Comment by tribouille** [comment]
Ok, that's weird :S 

Does your MediaInfoLib and ZenLib are up-to-date?
The report generated is not correct... and the crash could happen due to an internal error between interfaces.

If you have access to the CLI, can you try to do :
MediaConch -mi -fx /Users/o/Desktop/temp/ffv1_test_pixfmt-bgr0_coder-0_level-1.mkv
(I took the file path from the report) and see if the xml generated seems correct?

Thanks,

**Comment by JeromeMartinez** [comment]
> Does your MediaInfoLib and ZenLib are up-to-date?

@tribouille on Mac MediaInfoLib and ZenLib are embedded in the MediaConch binary.

**Comment by JeromeMartinez** [comment]
I can reproduce the crash.

**Comment by Elorrain** [comment]
@tribouille When using the CLI the XML seems correct, here's the full output:

$ MediaConch -mi -fx /Users/o/Desktop/temp/ffv1_test_pixfmt-bgr0_coder-0_level-1.mkv
<?xml version="1.0" encoding="UTF-8"?>
<MediaInfo
    xmlns="https://mediaarea.net/mediainfo"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://mediaarea.net/mediainfo https://mediaarea.net/mediainfo/mediainfo_2_0.xsd"
    version="2.0beta1">

<creatingLibrary version="0.7.83" url="https://mediaarea.net/MediaInfo">MediaInfoLib</creatingLibrary>
<media ref="/Users/o/Desktop/temp/ffv1_test_pixfmt-bgr0_coder-0_level-1.mkv">
<track type="General">
<UniqueID>28574085829540561427296791676590374400</UniqueID>
<Format>Matroska</Format>
<Format_Version>4</Format_Version>
<FileSize>6087801</FileSize>
<Duration>1.000</Duration>
<OverallBitRate>48702408</OverallBitRate>
<FrameRate>25.000</FrameRate>
<FrameCount>25</FrameCount>
<StreamSize>121147</StreamSize>
</track>

<track type="Video">
<StreamOrder>0</StreamOrder>
<ID>1</ID>
<UniqueID>1</UniqueID>
<Format>FFV1</Format>
<Format_Version>1</Format_Version>
<CodecID>V_MS/VFW/FOURCC / FFV1</CodecID>
<Duration>1.000</Duration>
<BitRate>47733232</BitRate>
<Width>640</Width>
<Height>480</Height>
<PixelAspectRatio>1.000</PixelAspectRatio>
<DisplayAspectRatio>1.333</DisplayAspectRatio>
<FrameRate_Mode>CFR</FrameRate_Mode>
<FrameRate>25.000</FrameRate>
<FrameCount>25</FrameCount>
<ColorSpace>RGB</ColorSpace>
<BitDepth>8</BitDepth>
<Compression_Mode>Lossless</Compression_Mode>
<Delay>0.000</Delay>
<StreamSize>5966654</StreamSize>
<Encoded_Library>Lavc56.26.100 ffv1</Encoded_Library>
<Default>Yes</Default>
<Forced>No</Forced>
<extra>
<coder_type>Golomb Rice</coder_type>
</extra>
</track>

</media>
</MediaInfo>

**Comment by tribouille** [comment]
Ok, thanks.
I suppose the github presentation destroyed the XML output...

We finally found the problem...
The Mac release was not compiled with SQLite support. So, the UI database was not correct.
And the backup for the no-SQL was buggy... Which makes the GUI crashing.

We're rebuilding the GUI with the correct support and debugging the wrong behavior.

**Comment by Elorrain** [comment]
Great ! Thanks.

**Comment by JeromeMartinez** [comment]
[Development snapshot](https://mediaarea.net/download/snapshots/binary/mediaconch-gui/20160312/MediaConch_GUI_16.02.20160312_Mac.dmg) is OK now.

**Comment by Elorrain** [comment]
Looks like it is fixed now with the new package. I don't get any crash anymore.
