### ISSUE TITLE
Policy: Dropdown for FFV1 version is string, but should be numeric

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#153]
When creating a policy in the GUI editor (which is already awesome, btw!), the dropdown-menu for "Video / Format Version" nicely lists options for "Version X", but the actual value should only numeric.
(See screenshot)

Steps to reproduce:
  1. Create new rule
  2. Track type=Video, Field=Format_Version
  3. Value= Select "Version 3" from the dropdown menu

The Value field will now literally be "Version 3" - which causes the policy check to fail.
The Value should have been only the number "3".

![mediaconch_045](https://cloud.githubusercontent.com/assets/2419195/19829067/d8f8abd4-9dd7-11e6-8c23-2505d13cfbc4.png)

**Comment by tribouille** [comment]
Right now, we only give "some" possible value independently of the context.
(These values are only suggestion)
Here, only the name and previous rule can hint on what is the expected value.

It is planned to make a filter on these values... (Not so easy to find the criteria)

**Comment by JeromeMartinez** [comment]
@tribouille actually version field is a bit special, as we removed "Version " from classic MediaInfo output and I did not think to ask you to support the special case.
Easy to change this specific case, not related to the dependently of the context (this is another issue, no easy, as you said).

**Comment by pjotrek-b** [comment]
Seems fixed in daily build "16.09.20161030":
Dropdown now offers the numeric-only options (without "Versions" prefixed string).

Excellent. Thank you! :cake:
