### ISSUE TITLE
Policy: "Track type" resets to undefined on "Duplicate"

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#154]
When copying a system policy to use in a user policy, using the "Duplicate" button, the "Track Type" option is reset to no value.

Example:
  1. Select: "System policy / CAVPP Preservation Master / Audio is 48kHz"
  2. Press Duplicate
  3. The copied instance of this rule will **not have the track type** set to "Audio", but undefined.

**Comment by tribouille** [comment]
Done here: https://github.com/MediaArea/MediaConch_SourceCode/pull/440
