### ISSUE TITLE
Policy editor: Export creates broken XML on overwrite

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#161]
I've created a policy set, then exported it to XML - but updating (overwriting) an already existing previous version of the XML.

Trying to import that policy throws the error: "The schema given cannot be parsed"
**The error is actually that the XML is broken, because it contains the rest of the old XML at the end.**

**Steps to reproduce:**

  1. Export any policy with at least a few rules to XML
  2. Remove one of these rules and export to the **same XML**
  3. Confirm to overwrite the existing file.

The resulting XML file contains leftovers from the longer export at the bottom.

Version 16.09.20161030 / Xubuntu 12.04 (64bit)

**Comment by tribouille** [comment]
Ok, I can reproduce it.
