### ISSUE TITLE
Description in .deb files is same for all packages

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#165]
For my own convenience (and fun), I've set up a repository with MediaConch packages for Debian 8 (Jessie).

When running "apt-cache search mediaconch", I get this:
  > mediaconch - Implementation checker, policy checker, reporter, and fixer
  > mediaconch-gui - Implementation checker, policy checker, reporter, and fixer
  > mediaconch-server - Implementation checker, policy checker, reporter, and fixer

Would it be possible to change the package descriptions to indicate their different purpose?

Suggestion:
  > mediaconch - Checks media files (policy, implementation, etc) - command line version
  > mediaconch-gui - Checks media files (policy, implementation, etc) - GUI version
  > mediaconch-server - Checks media files (policy, implementation, etc) - server version

I btw took the liberty of also suggesting a different description, as the current one doesn't say what files it checks.

**Comment by tribouille** [comment]
FYI, you can find those information here: https://github.com/MediaArea/MediaConch_SourceCode/blob/master/debian/control
If you want to make the change, feel free :)
(You already have done most of the work to do)

**Comment by pjotrek-b** [comment]
Roger that :)
Thanks!

**Comment by g-maxime** [comment]
Solved in https://github.com/MediaArea/MediaConch_SourceCode/commit/d158c3349b41bc83799b1e44e5adb7faba01ed44
