### ISSUE TITLE
MediaConch website menu not working in previous FF versions

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#167]
On Ubuntu 12.04 (LTS) Firefox v45.0, the menu on the MediaConch website (About / Documentation / Software) is not working.

Haven't tried with newer FF yet, but it works with Chromium (v37).

**Comment by JeromeMartinez** [comment]
For info I can not reproduce on FF v45.0 Windows not FF v45.3ESR Windows. Weird (usually same engine whatever it the OS).
For developers with a Linux!

**Comment by retokromer** [comment]
FYI: Works fine on Ubuntu 16.04 LTS (and Firefox 49.0.2).

**Comment by g-maxime** [comment]
Works with Firefox 45.0 on Gentoo, I will try with an older distribution...

**Comment by pjotrek-b** [comment]
Don't bother... I'll recheck my setup.
