### ISSUE TITLE
Implementation checks missing tests (install issue?)

### ISSUE THREAD

**Issue by jrwdunham** [MediaArea/MediaConch#171]
I'm using MediaConch v. 16.10 and I'm finding that I am no longer able (since migrating from 16.05 to 16.10) to determine whether a .mkv file passes the implementation check. This is on Ubuntu 14.04.

I have been using the invalid_ebml files at https://github.com/dericed/matroska-test-files/tree/invalid-ebml/invalid_ebml for testing. A command like the following:

    $ mediaconch -mc -iv 5 -fx invalid_ebml/crc_element_has_invalid_hash.mkv

returns only 4 `<check>` elements, all of which contain `<test outcome="pass">`
elements and have `fail_count="0"` attributes.

However, when I use https://mediaarea.net/MediaConchOnline/checker (e.g., the ffv1_test_pixfmt-bgr0_coder... "server file") I see much more output for (failed) implementation checks (`<check>` elements) and I clearly see `outcome="fail"` attributes in `<test>` elements. Other users have confirmed more output than what I am seeing.

My MediaConch installation is effected via a sequence of Ansible commands. See https://github.com/artefactual-labs/ansible-archivematica-src/blob/dev/install-mediaconch/tasks/pipeline-deps.yml#L42-L99. Another users who installed via this method got the same results. Is there something wrong with these commands or is there a dependency that I might need to update? Thanks for the help.

**Comment by tribouille** [comment]
Hi,

you also have to update your MediaInfoLib (In your Ansible commands, it says to install the 0.7.86... for MC 16.10, you need the 0.7.90)

But, you should use the latest release of MediaConch and MediaInfoLib (and ZenLib).
MediaConch == 16.12: https://mediaarea.net/download/binary/mediaconch/
MediaInfoLib == 0.7.91: https://mediaarea.net/download/binary/libmediainfo0/

MCO is using the latest release.

Note: "-iv 5" is the default verbosity, not needed.

**Comment by JeromeMartinez** [comment]
> (In your Ansible commands, it says to install the 0.7.86... for MC 16.10, you need the 0.7.90)

I am surprised, does Ansible bypass the dependency rules? it is [explicitely said that mediaconch 16.10 needs libmediainfo 0.7.90](https://github.com/MediaArea/MediaConch_SourceCode/blob/98ba940dea884a3a8c7d7e1d61f9275c023c9fa0/debian/control#L7)

**Comment by jrwdunham** [comment]
Yes, thanks, upgrading to the most recent versions of libmediainfo (and libzen) seemed to fix the issue for me. Running mediaconch 16.12, libmediainfo 0.7.91 and libzen0.4.34, everything appears to be working correctly. Thanks for your help.

**Comment by JeromeMartinez** [comment]
FYI we are adding the missing check on version during .deb install (the check was done only during the build, and not automatically propagated to the .deb itself)
