### ISSUE TITLE
[v18] add man to mediaconch CLI

### ISSUE THREAD

**Issue by retokromer** [MediaArea/MediaConch#173]
In order to be able to better work offline, not having access to the internet.

**Comment by JeromeMartinez** [comment]
Actually there is no exhaustive documentation about CLI options, only "mediaconch --help", so it would be also for "online" people.

**Comment by retokromer** [comment]
I mean a more complete information than given by the `-h` option, i.e. the details of the listed parameters. In my opinion, those details would overload the `-h`, but would be useful in an additional man which would be available when the CLI is installed.

**Comment by JeromeMartinez** [comment]
Sorry, I wanted to mean that: we need more exhaustive documentation, for both online and offline.
