### ISSUE TITLE
Different Checking results for same file

### ISSUE THREAD

**Issue by verwinv** [MediaArea/MediaConch#177]
Hi, 

- generated a general conformance file according to [these instructions](https://mediaarea.net/MediaConch/demo.html)

- according to MediaConch it is Not valid 
<img width="800" alt="item-0_and_window_and_item-0" src="https://cloud.githubusercontent.com/assets/6201005/23788221/d2d25efc-0575-11e7-994d-b049945942c7.png">

- according to MediaConchOnline it is Valid. 
<img width="800" alt="screenshot 2017-03-10 09 35 50" src="https://cloud.githubusercontent.com/assets/6201005/23788194/c054fbae-0575-11e7-9a82-0c55dfeeb008.png">

What is going awry here?

**Comment by JeromeMartinez** [comment]
Which version of MediaConch are you using?
I tested with latest release 17.02 and I have same results as MediaConchOnline.

It may be due to an old test on an element not actually being mandate (I see 44 tets in your MC and only 43 on my MC 17.02).

**Comment by verwinv** [comment]
Version 16.12, indeed. 

But that's odd as I did `brew cask reinstall mediaconch-app` just before trying. Does the brew version lag behind other channels?

**Comment by JeromeMartinez** [comment]
Weird, [Brew Cask repo is with MediaConch 17.02](https://github.com/caskroom/homebrew-cask/blob/master/Casks/mediaconch-app.rb).
@g-maxime any idea?

**Comment by retokromer** [comment]
@verwinv Have you tried?
```
brew update
brew upgrade
```

**Comment by g-maxime** [comment]
Try updates brew repository, then reinstall mediaconch-app
`brew update && brew cask install --force mediaconch-app`

**Comment by verwinv** [comment]
Thanks all, I was using `brew upgrade` only and `reinstall` which seems to be not enough.
