### ISSUE TITLE
v17.02 Windows 7: "api-ms-win-crt-runtime-l1-1-0.dll is missing"

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#179]
Installed MediaConch v17.02 (GUI) on Windows 7 Home-Premium (64bit).
Install works fine, but when I try to start Mediaconch, I get the following error message:

> The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is 
> missing from your computer. Try reinstalling the program to fix this problem.

MediaConch won't start at all.

**Comment by pjotrek-b** [comment]
Haven't tried with a daily-build/snapshot, as it seems there are none for Windows here:
https://mediaarea.net/MediaConch/downloads/snapshots.html

**Comment by JeromeMartinez** [comment]
You are using an outdated Windows 7. For your security, you should update it (SP1 + updates).
If for any reason you can not do it, you can install a standalone package: [Update for Universal C Runtime in Windows](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows).

As this package is on any up to date Windows, we don't plan to include it in the installer (bigger size for very few people), if there are more people complaining about this issue we could add a dynamic check and download the package, but this is not the plan yet.

For the snapshot, the last one failed tonight on Windows, we are working on it and we need to find a method for linking to the latest available.

**Comment by pjotrek-b** [comment]
Thanks for clearing that up!
Actually, I did install SP1 but I'll check again :)

**Comment by JeromeMartinez** [comment]
hum... It is expected to be in one of the updates, I thought it was SP1, maybe it is another later update, argh.Without being sure, I understood that any up to date Windows gets it, weird.
