### ISSUE TITLE
improper utf-8 error

### ISSUE THREAD

**Issue by bturkus** [MediaArea/MediaConch#204]
hi,

i've got a v210/mov (exported from Adobe Premiere Pro CC 2018, Version 12.0.0) that's generating the following error message in MediaConch (GUI macOS Version 17.11):

Validation generated an internal error: Entity: line 119:  parser  error :  Input is not proper UTF-8, indicate encoding !
Bytes: 0xA9 0x54 0x49 0x4D
 ame">FIEL</d></b><d o="4104" n="Data">(18 bytes)</d></b><b o="4122" n="Text" i="

Any ideas what's behind this? I'd be happy to share a tiny file, or any other relevant details. Thanks!

**Comment by JeromeMartinez** [comment]
Looks like  duplicate of https://github.com/MediaArea/MediaConch_SourceCode/issues/630

**Comment by bturkus** [comment]
whoops. my bad! I searched for "UTF," but didn't think to check the other repos. closing...
