### ISSUE TITLE
Link to "Activate MediaArea Repository" wrong?

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#209]
On the Mediaconch download page for Ubuntu, there is a link to "[Activate MediaArea Repository](https://mediaarea.net/Repos)", but instead of pointing to some repository information, it leads to the default MediaInfo page.

**Comment by JeromeMartinez** [comment]
Redirection is not working, it should redirect to https://mediaarea.net/en/Repos
I wonder if we should really redirect (no translated page)

**Comment by pjotrek-b** [comment]
Links behave correct now. Seems fixed.
