### ISSUE TITLE
FFV1-SLICE-sar_den fail

### ISSUE THREAD

**Issue by privatezero** [MediaArea/MediaConch#210]
I referenced this in https://github.com/MediaArea/MediaInfoLib/issues/782, but as it appears to be a slightly different issue, and I was able to recreate the problem with a sample piece of the problematic file I figured I should make a new issue. This is found during MediaConch checks of this particular FFV1/MKV file, but none of the others created in the same batch.

Error:
> FFV1-SLICE-sar_den Tests run: 4 | Results: ❌ Fail count: 4
Results: fail ❌ 
Name: sar_den
Offset: 1233
Value context: /Segment[1]/Cluster[1]/SimpleBlock[1]/Data[1]/Frame[1]/Slice[1]/SliceHeader[1]
Value: 1
Results: fail ❌ 
Name: sar_den
Offset: 17294
Value context: /Segment[1]/Cluster[1]/SimpleBlock[1]/Data[1]/Frame[1]/Slice[2]/SliceHeader[1]
Value: 1
Results: fail ❌ 
Name: sar_den
Offset: 33355
Value context: /Segment[1]/Cluster[1]/SimpleBlock[1]/Data[1]/Frame[1]/Slice[3]/SliceHeader[1]
Value: 1
Results: fail ❌ 
Name: sar_den
Offset: 49417
Value context: /Segment[1]/Cluster[1]/SimpleBlock[1]/Data[1]/Frame[1]/Slice[4]/SliceHeader[1]
Value: 1

Sample File: https://drive.google.com/open?id=1pTZh9-8o11G4ndsc75j_kvy6t2v3_7ju

**Comment by JeromeMartinez** [comment]
Different issue, right.
I was actually digging in this issue for another work, looks like there is a disagreement between draft of FFV1 spec (0/0 if unknown) and FFmpeg (0/1 if unknown), we need to clarify that with FFmpeg and FFV1 spec people, in the meanwhile I'll accept any SAR denominator even if SAR numerator is 0.

**Comment by privatezero** [comment]
Cool - thank you!!

**Comment by JeromeMartinez** [comment]
[latest snapshot](https://mediaarea.net/download/snapshots/binary/mediaconch-gui) contains the fix. Public release next week, please review before the release if possible.
You need to clear the database, " --force" for each file with CLI (or drop the database), "Database" then "Delete all results from database" in GUI.
