### ISSUE TITLE
Policy check for video also running on embedded attachments

### ISSUE THREAD

**Issue by aeschweik** [MediaArea/MediaConch#211]
I'm trying to embed sidecar digitization logs in FFV1/Matroska files (using mkvpropedit). When I run the resulting .mkv file through a local FFV1 policy check, the video file passes, but the attachments appear to be parsed out and run through the same policy check, which of course they fail since they're text files. 

Is there any way to avoid running a policy check on Matroska attachments? It has been working great otherwise - thanks!

```
pass! /private/tmp/test32o4u254_ffv1.mkv
fail! attachment:/private/tmp/test32o4u254_ffv1.mkv:test32o4u254_capture_options.log
fail! attachment1:/private/tmp/test32o4u254_ffv1.mkv:test32o4u254_ffmpeg_decklink_input.log
fail! attachment2:/private/tmp/test32o4u254_ffv1.mkv:test32o4u254_ffv1.mkv.qctools.xml.gz
```

**Comment by JeromeMartinez** [comment]
Happy to see that the tool is useful.
The behavior you are facing was not expected, and definitely not the right way, at least when it is not customable.

**Comment by JeromeMartinez** [comment]
[We don't apply anymore policies to attachments](https://github.com/MediaArea/MediaConch_SourceCode/pull/638), in [snapshots](https://mediaarea.net/download/snapshots/binary/mediaconch/) and next official release.

**Comment by aeschweik** [comment]
Thanks!!
