### ISSUE TITLE
rawcooked invalid MKV files

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/MediaConch#213]
I am using Ubuntu 18.04. It seems like any file made by rawcooked that I put through mediaconch results in similar errors as below.
I am attaching the sample DPX and rawcooked MKV.
```
$ mediaconch -v
MediaConch Command Line Interface 18.03.2

$ mediaconch fakedpx.mkv 
fail! fakedpx.mkv
 -- MKV-ELEMENT-VALID-PARENT
 --    [fail:FileData is not a valid Parent Element of A45DFA3.]
 --     [/Segment[1]/Attachments[1]/AttachedFile[1]/FileData[1]/A45DFA3[1] at bytes offset of 789]
 --    [fail:FileData is not a valid Parent Element of 7273.]
 --     [/Segment[1]/Attachments[1]/AttachedFile[1]/FileData[1]/7273[1] at bytes offset of 814]
 --    [fail:FileData is not a valid Parent Element of RawcookedTrackEntry.]
 --     [/Segment[1]/Attachments[1]/AttachedFile[1]/FileData[1]/RawcookedTrackEntry[1] at bytes offset of 838]
 --    [fail:FileData is not a valid Parent Element of RawcookedBlock.]
 --     [/Segment[1]/Attachments[1]/AttachedFile[1]/FileData[1]/RawcookedBlock[1] at bytes offset of 949]
! attachment:fakedpx.mkv:rawcooked reversibility data
```
 
[fakedpx.zip](https://github.com/MediaArea/MediaConch/files/2637085/fakedpx.zip)

My ffmpeg version:

```
$ ffmpeg
ffmpeg version N-92521-g737b5f5869 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: 
  libavutil      56. 24.101 / 56. 24.101
  libavcodec     58. 40.100 / 58. 40.100
  libavformat    58. 23.100 / 58. 23.100
  libavdevice    58.  6.100 / 58.  6.100
  libavfilter     7. 46.100 /  7. 46.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

```

**Comment by JeromeMartinez** [comment]
Some incoherencies here in the way we handle EBML content in a file in attachments, we definitely need to have something more coherent here.

**Comment by kieranjol** [comment]
The attachment shows up as a different file in the mediaconch gui:
![screenshot from 2018-12-02 15-57-28](https://user-images.githubusercontent.com/1127102/49341840-07e18380-f64b-11e8-8969-d104ffd4ad5f.png)

**Comment by JeromeMartinez** [comment]
> The attachment shows up as a different file in the mediaconch gui

This is wanted, in order to validate also attachments. Unfortunately we "forgot" to limit the test to Matroska when we find EBML content, and RAWcooked uses EBML.
Definitely a use case we need to handle correctly.

**Comment by retokromer** [comment]
Indeed, this should be handeled correctly.

Thank you, @kieranjol, for reporting!

**Comment by genfhk** [comment]
@JeromeMartinez , I lost my own thread about this somewhere and someone may have already suggested this, but seeing as this issue is still open, I figured I'd ask here - is there a way to ignore attachments? 

I'm still dealing with RAWcooked reversibility data failing mediaconch.

**Comment by JeromeMartinez** [comment]
@genfhk it was fixed in https://github.com/MediaArea/MediaConch_SourceCode/pull/674.
We didn't do a public release since the PR is merged, but [snapshots](https://mediaarea.net/download/snapshots/binary/) should have a correct behavior (it is fine with my tests).
I forgot to close the ticket, doing it now.

**Comment by genfhk** [comment]
oh duh. ty!
