### ISSUE TITLE
No bitrate for video and audio streams in a TS file

### ISSUE THREAD

**Issue by XMegamanX** [MediaArea/MediaConch#221]
Hello !
I would like to test the bitrate of the different streams of a TS file. The problem is that MediaConch does not have access to these data. The only bitrate available is the overall one. Is it a particularity from the container ?

Regards

Megaman

**Comment by JeromeMartinez** [comment]
TS has no info about the bitrate per stream.
When the TS has only one VBR stream i.e. when audio is CBR, we do some estimation (overall bitrate - TS overhead - audio bitrate), but if you want more we need to parse the whole file (not only a part as it is done by default). It is doable, but longer.

You can try with command line by adding ` --ParseSpeed=1` (or "full parse" option in the GUI) but not tested myself, if bitrate is showed you have what you look for, else we would have to do some development (in that case, priority would depends on [sponsorship](//mediaarea.net/Services)).

**Comment by XMegamanX** [comment]
Thanks for the quick reply, it is clear :). I will try with ParseSpeed.

**Comment by XMegamanX** [comment]
Hello ! 
`--ParseSpeed=1` doees s the trick. I am now able to get the bitrate of the video and audio tracks. But does it comes from a full parsing of the file or just a part of it ? I mean, is the returned value accurate ?

Regards

Megaman

**Comment by JeromeMartinez** [comment]
> I mean, is the returned value accurate ?

I expect it to be accurate but there is no warranty on that, I have made lot of modifications in the code and I didn't really focus on that right now, it needs more checks of the code if you want to be 100% sure.
Being sure it is the real count of bytes (so bitrate) is planned but no ETA (depends on sponsorships).

**Comment by XMegamanX** [comment]
Ok thank you very much for your time :)
