### ISSUE TITLE
CC 708 Tracks in MediaConch Broken?

### ISSUE THREAD

**Issue by jsciame** [MediaArea/MediaConch#227]
I'm attempting to run MediaConch against QuickTime MOV files with embedded 608 and 708 closed captions. The MediaConch is not identifying the  608 or 708 tracks.

Running MediaInfo outside of MediaConch.

Text #1
ID                                       : 2-CC1
Format                                   : EIA-608
Muxing mode                              : Final Cut / CDP
Codec ID                                 : c708
Duration                                 : 37 s 37 ms
Start time (commands)                    : 7 s 174 ms
Start time                               : 7 s 274 ms
End time                                 : 17 s 351 ms
End time (commands)                      : 17 s 351 ms
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)
Language                                 : English
Forced                                   : No
Encoded date                             : UTC 2020-04-21 00:36:06
Tagged date                              : UTC 2020-04-21 00:36:09
Count of PopOn events                    : 4
Count of PaintOn events                  : 2
Count of events                          : 6
FirstDisplay_Delay_Frames                : 230
FirstDisplay_Type                        : PaintOn

Text #2
ID                                       : 2-1
Format                                   : EIA-708
Muxing mode                              : Final Cut / CDP
Codec ID                                 : c708
Duration                                 : 37 s 37 ms
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)
Language                                 : English
Forced                                   : No
Encoded date                             : UTC 2020-04-21 00:36:06
Tagged date                              : UTC 2020-04-21 00:36:09

MediaConch Result

<policy name="TEXT" type="or" rules_run="2" pass_count="0" fail_count="2" outcome="fail">
              <description>TEXT</description>
              <tag>TEXT_CAPTIONS</tag>
              <rule name="Format is EIA-608" value="Format" tracktype="Text" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type=&apos;Text&apos;][*]/mi:Format" requested="EIA-608" actual="" outcome="fail"/>
              <rule name="Text/CodecID is c708" value="CodecID" tracktype="Text" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type=&apos;Text&apos;][*]/mi:CodecID" requested="c708" actual="" outcome="fail"/>
            </policy>

Policy

<policy type="or" name="TEXT">

					<description>TEXT</description>

					<tag>TEXT_CAPTIONS</tag>

					<rule name="Format is EIA-608" value="Format" tracktype="Text" occurrence="*" operator="=">EIA-608</rule>
					<rule name="Text/CodecID is c708" value="CodecID" tracktype="Text" occurrence="*" operator="=">c708</rule>

				</policy>

MediaConch Command Line Interface 18.03.2.20220117
MediaConch GUI 18.03.2.20211214
MediaInfo Command line, MediaInfoLib - v21.09

When I import the file into policy to create a policy from file, MediaConch does not show the text tracks.  I'm happy to send the sample file if you need it, but I'm attaching the full MediaInfo and MediaConch Reports.

[MediaInfo.txt](https://github.com/MediaArea/MediaConch/files/7892375/MediaInfo.txt)
[MediaConch.txt](https://github.com/MediaArea/MediaConch/files/7892344/MediaConch.txt)
[Ad_Apple_iPadPro.mov_MediaInfo.xml.zip](https://github.com/MediaArea/MediaConch/files/7892360/Ad_Apple_iPadPro.mov_MediaInfo.xml.zip)

**Comment by JeromeMartinez** [comment]
I tried the Windows GUI and CLI and can get the 608/708 from a MOV with c708 codecid, and this is the output from MediaConch Command Line Interface 18.03.2.20220117 Windows:
[608_in_c708.MediaInfo.xml.txt](https://github.com/MediaArea/MediaConch/files/7928709/608_in_c708.MediaInfo.xml.txt)

And it works with the policy:
[608_in_c708.Policy.xml.txt](https://github.com/MediaArea/MediaConch/files/7928713/608_in_c708.Policy.xml.txt)

Maybe a specific issue with your file.
Please try the latest version of the [Online policy checker](https://mediaarea.net/temp/policy-checker/HowToUse.html) (it is up to date), if still the issue I need the specific file.

For reference with my file I have:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<MediaConch xmlns="https://mediaarea.net/mediaconch" xmlns:mmt="https://mediaarea.net/micromediatrace" xmlns:mi="https://mediaarea.net/mediainfo" version="0.3" verbosity="0">
  <media ref="SS11202H.mov">
    <policy name="608 in c708" type="and" rules_run="2" fail_count="0" pass_count="2" outcome="pass">
      <description>TEXT</description>
      <tag>TEXT_CAPTIONS</tag>
      <rule name="Format is EIA-608" value="Format" tracktype="Text" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Text'][*]/mi:Format='EIA-608'" outcome="pass"/>
      <rule name="Text/CodecID is c708" value="CodecID" tracktype="Text" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Text'][*]/mi:CodecID='c708'" outcome="pass"/>
    </policy>
  </media>
</MediaConch>
```

**Comment by JeromeMartinez** [comment]
Reproduced with a HTTP link.
Fixed by [removing a specific configuration](https://github.com/MediaArea/MediaConch_SourceCode/pull/713) of MediaInfo library in MediaConch, better to use MediaInfo library defaults.
