### ISSUE TITLE
Feature Request: Detect Timecode Discontinuity

### ISSUE THREAD

**Issue by jsciame** [MediaArea/MediaConch#231]
I’ve got a sample file that has timecode discontinuity. Is this something that can be seen by MediaInfo or MediaTrace so that it can be detected in MediaConch?

If you look at the timecode in a player, the timecode goes from 00:00:00:00 –> 00:00:06:23 -> 00:00:04:00

As we discussed over email, you mentioned this is possible. As requested we'd like the ability to detect timecode discontinuity as well as the timecode values where there is discontinuity.

**Comment by jsciame** [comment]
@JeromeMartinez I did some testing of this in the **20220709** snapshot build.

Running the following command over an over, I get different results each time I run this but it does detect that there are discontinuities. Do you know what is causing these odd time values before the actual time discontinuity values?

Run 1: `Discontinuities : 37:32:52:07-00:00:00:01 / 00:00:06:23-00:00:04:01`
Run 2: `Discontinuities : 00:00:06:23-00:00:04:01`
Run 3: `Discontinuities : 157:46:23:10-00:00:00:01 / 00:00:06:23-00:00:04:01`

Command: `mediainfo -f /Users/jsciame/Downloads/HAFLZ164067H.mov --ParseSpeed=0.7`

Also, the file we are testing doesn't find the issue in MediaInfo unless I set the ParseSpeed to 0.7. Do you know when you'll add the ability in MediaConch to set the ParseSpeed?  

Have a great weekend.

**Comment by JeromeMartinez** [comment]
> Also, the file we are testing doesn't find the issue in MediaInfo unless I set the ParseSpeed to 0.7. Do you know when you'll add the ability in MediaConch to set the ParseSpeed?

This option is already available in MediaConch, command line or JS.

We check for the random behavior.

**Comment by JeromeMartinez** [comment]
> I get different results each time I run this

[Fixed](https://github.com/MediaArea/MediaInfoLib/pull/1567).
