### ISSUE TITLE
Existing policy appears to be broken by daily build

### ISSUE THREAD

**Issue by privatezero** [MediaArea/MediaConch#232]
I have a relatively simple policy (see [at this gist](https://gist.github.com/privatezero/f8c2639e1fe5387c565d0ea4f2313e64)) for checking if a BEXT chunk exists in a WAV file that uses the MediaTrace rule type, and something appears to have changed in the daily builds that causes an error with the policy.

See the following two reports (Both made on Ubuntu).  I noted that the report made with the daily build lacks the xpath information present in the report made with version 22.03.

[output-22.03.txt](https://github.com/MediaArea/MediaConch/files/9162981/output-22.03.txt)
[output-22.03.20220719.txt](https://github.com/MediaArea/MediaConch/files/9162980/output-22.03.20220719.txt)

MediaTrace report for input file in [this gist](https://gist.github.com/privatezero/8cf47049337000932e34f72e989016eb)

**Comment by JeromeMartinez** [comment]
@privatezero please test the latest development snapshot.
We are working on a new and more versatile engine for the policy checker, and we forgot that policies checking custom element in the "trace" of the file ("mnt") is not yet supported, in the meanwhile we keep the old parser in that case.

**Comment by privatezero** [comment]
@JeromeMartinez that's taken care of it! Thank you for all your ongoing development on this!
