### ISSUE TITLE
Differences between Meciaconch Policy and Schematron?

### ISSUE THREAD

**Issue by ross-spencer** [MediaArea/MediaConch#236]
I am looking for information about Mediaconch's use of Schematron and where the two departed. I can see in the [original release](https://www.digitalmeetsculture.net/article/initial-release-of-mediaconch-now-available/) Schematron was a core part of a policy's implementation. Since then, there are still [references to historical issues and commits](https://github.com/search?q=repo%3AMediaArea%2FMediaConch%20schematron&type=code) about its use but I don't see anything overt about it. The policies still seem to share the same DNA. Did the two approaches divert? Or did Mediaconch abstract some of the Schematron details away to make it easier to use? (or something else?)

Any information appreciated, thanks all!

**Comment by JeromeMartinez** [comment]
We don't use Schematron anymore as is, while keeping the idea, right.
We focus on our policy XML, easier to edit and maintain.
Nothing really against Schematron itself, not really something we did on purpose, it was just how it happened when we added new features, Schematron could come back if there is a sponsor wanting it.

**Comment by ross-spencer** [comment]
Thanks @JeromeMartinez I had just been looking for user-stories around it, but that makes sense, and the rationale makes good sense as well. (Nb. I'm not looking for Schematron per se. the XML requirements are too heavy. Would be interesting to see similar tooling with JSON).

**Comment by JeromeMartinez** [comment]
> Would be interesting to see similar tooling with JSON

when someone needs (= ready to sponsor it) it, easy to have JSON input in addition to XML input for the policy.
