### ISSUE TITLE
create mockup images for metadata fixer ui

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaConch#41]
I think the functional requirements documentation of the metadata fixer is sufficient to set up some images for support the reports or presentation.

https://github.com/MediaArea/PreFormaMediaInfo/blob/6a81950431b7ca4fdcb5b878e37faf1f8b99590c/Design/GUI/MKVMetadataFixer.md

**Comment by ablwr** [comment]
The fixer has significantly changes in the past... nearly two years. I am closing this ticket.
