### ISSUE TITLE
document difference between the ebml rfc draft and current ebml spec

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaConch#64]
From matroska-devel http://lists.matroska.org/pipermail/matroska-devel/2015-April/004623.html, Moritz says that the RFC draft at http://matroska.org/technical/specs/rfc/index.html is an abandoned draft and not authoritative, but that http://matroska-org.github.io/libebml/ should be referenced.
But the RFC draft has sensible things in it that aren't in specs like: "Note that the shortest
   encoding form for 127 is 0x407f since 0x7f is reserved".
I propose we itemize out the differences between the RFC draft and the ebml specs to submit to matroska-devel for consideration.

**Comment by epiil** [comment]
For itemizing out the differences, are you referring to the elements semantic sections for both documents?

**Comment by dericed** [comment]
Mainly, I want to itemize things of value from the RFC draft that aren't in the specs, so that they could be considered for incorporation into the specs.

**Comment by epiil** [comment]
The Nilsson ebml draft is copyrighted - should that have any weight on this
task?

**Comment by epiil** [comment]
I compared the elements semantic of the two documents in https://github.com/MediaArea/MediaConch/blob/master/ConformityChecks/EBMLSpecsComparison.csv

Going through the remaining text now to pull sensible things.

**Comment by dericed** [comment]
Not happened. The EBML RFC draft referenced here is at http://matroska.org/technical/specs/rfc/index.html, which is problematic since Matroska does not control the copyright for that work. This effort has been fully superseded by the IETF Cellar Working Group.
