### ISSUE TITLE
Feature request : export toolbar option and/or button for MediaConch GUI

### ISSUE THREAD

**Issue by epiil** [MediaArea/MediaConch#71]

**Comment by tribouille** [comment]
Hi Erik,

can you provide a little bit more information about what you want?

What do you want to export?
* The result given by MediaConch?
* Something else?

How? (I suppose to save it into a file)

Best regards,
-- 
Florent

**Comment by epiil** [comment]
Hi Florent,

**Comment by epiil** [comment]
Hi Florent, 

As it stands I think it would be appropriate to have export options for the following readouts/reports:

1) Implementation Checker (Conch) in .TXT and .XML (upon completion)
2) MediaInfo General Readout in .TXT and .XML
3) MediaTrace in .TXT and .XML (upon completion, although I believe .XML will be preferred here)

Export as in, "Save to File."

Thanks, 

Erik

**Comment by tribouille** [comment]
Done with the last GUI
