### ISSUE TITLE
Repo request: A repository specifically for MediaConch sample files

### ISSUE THREAD

**Issue by ablwr** [MediaArea/MediaConch#72]
@JeromeMartinez Jerome, can you create a new repo for MediaConch sample files? And @epiil can you move the test files into it when it exists?

**Comment by JeromeMartinez** [comment]
https://github.com/MediaArea/MediaConch_SampleFiles

**Comment by epiil** [comment]
Jerome,

Do I need permission to access MediaConch_SampleFiles? I'm having trouble
pushing commits and it appears to be a permissions issue.

Best,

Erik

**Comment by JeromeMartinez** [comment]
All MediaConch developers have write permission.

**Comment by GuillaumeRoques** [comment]
@epiil 
I added write permissions to you and the team.

Guillaume

**Comment by epiil** [comment]
Thanks Guillaume, it appears to be working now.
