### ISSUE TITLE
Broken schematron links on MediaConch demo page

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#73]
On the [MediaConch Demo page](https://mediaarea.net/MediaConch/demo.html), all links pointing to schematron files seem to be invalid :(

For example:
https://mediaarea.net/MediaConch/Files/Test1_pal.sch

**Comment by dericed** [comment]
Sorry about that. we're in the process of updating the schematron to xslt.

**Comment by pjotrek-b** [comment]
Just wanted to let you know :)
Meanwhile, I've used the files [directly from the repository](/MediaArea/MediaConch/tree/master/Demo/Files)

**Comment by JeromeMartinez** [comment]
Fixed.

**Comment by pjotrek-b** [comment]
Verified.
Thanksalot :)
