### ISSUE TITLE
Encoding issue in policy report in GUI

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#74]
It seems that policy error encoding isn't using the encoding specified in the schematron XML.

Example with the [NTSC policy file](/MediaArea/MediaConch/blob/master/Demo/Files/Test1_ntsc.sch):
The XML encoding is specified as UTF-8, but displayed like this in the MediaConch GUI:
> /Mediainfo/File line 5: Framesize must be 720 Ã 480.

**Comment by JeromeMartinez** [comment]
the Schematron file is in UTF-8, unfortunately the result has no explicit encoding (this is raw text, not UTF-8).
But we should definitely consider the output as UTF-8.

FYI, we are moving to XSLT and a XML output, so encoding will be explicit.

**Comment by pjotrek-b** [comment]
I've also noticed that embedded metadata (e.g. title, artist, etc) encodings read from media files are also affected by the encoding of the raw text display at the moment.

**Comment by JeromeMartinez** [comment]
same source of the issue

**Comment by tribouille** [comment]
Reports are displayed in UTF-8 now, should be ok.
