### ISSUE TITLE
Hardcoded policies?

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#76]
In MediaConch GUI, the "Conch" report shows "Pass" or "Fail" for certain properties - even if there is no policy set loaded at all.

When adding/applying policies manually, they don't seem to overload the default (hardcoded/built-in) ones.

Is that on purpose?

**Comment by JeromeMartinez** [comment]
@pjotrek-b is this issue still relevant with MediaConch 15.11?
I think the behavior is "logical" now.

**Comment by pjotrek-b** [comment]
Must check.
Couldn't do this yet, due to issues with v15.11 on Linux (Ubuntu).

**Comment by JeromeMartinez** [comment]
If you speak of issue with "v5" stuff, issues with v15.11 on Ubuntu are expected to be fixed, please download again the packages (they are replaced) and test again.

**Comment by pjotrek-b** [comment]
Did so now.
Seems to be fine for policy rules :)

Yet, the "Implementation report" always fails if the input file is not MKV.

This makes perfect sense for the current requirements (FFV1/PCM/MKV), but I find it sad, because the underlying engine seems to be capable to be used for other formats already (and possibly add implementation checks for other containers in the future?)

Sorry for this bold "offer inch - take a mile" request ;)

**Comment by JeromeMartinez** [comment]
> Yet, the "Implementation report" always fails if the input file is not MKV.

Maybe we could find a better way to say that this is not the expected format e.g. "Not applicable" if it is not MKV (we'll add TIFF and PDF in the "accepted" formats, using other PREFORMA projects, so they'll also be not "invalid").
@dericed your thoughts?

> because the underlying engine seems to be capable to be used for other formats already

Right. But currently no rules are defined by us for other formats (so you need to create yourself a XSL to apply to the analysis i.e. to MediaTrace XML and load the XSL as a policy).
Just to be clear: implementation report is "only" an hard-coded policy, so you can adapt the XSL files for other formats. We'll provide documentation about such possibility.

> (and possibly add implementation checks for other containers in the future?)

Looking for sponsors ;-).

**Comment by dericed** [comment]
I moved the discussion on "Yet, the "Implementation report" always fails if the input file is not MKV." to https://github.com/MediaArea/MediaConch/issues/103. Also I hope to have some demo of non-mkv-ffv1-pcm in implementationCheck ready before April. Hopefully a simple format like WAV or DPX.
