### ISSUE TITLE
Links to xsl examples broken in readme

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/MediaConch#82]
I wanted to look at some examples in the demo section and all the xsl files were moved elsewhere: 
https://github.com/MediaArea/MediaConch/tree/master/Demo
I was gonna repair the links but wasn't sure if it was intentional.

**Comment by JeromeMartinez** [comment]
It was not

**Comment by epiil** [comment]
Links should be repaired now on this page - thanks Kieran.

**Comment by kieranjol** [comment]
Looks good, thanks guys.
