### ISSUE TITLE
library .deb packages for Ubuntu Precise (12.04 LTS) fail dependencies

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#84]
I've downloaded the packages for libzen0, as well as libmediainfo0, provided on the [MediaConch download site](https://mediaarea.net/MediaConch/downloads/ubuntu.html).

Trying to install them, however leads to error messages:

1) libzen0_0.4.32-1_amd64.xUbuntu_12.04
> Error: Breaks existing package 'libzen-dev' dependency libzen0 (= 0.4.23-1ubuntu1)

2) libmediainfo0_0.7.80-1_amd64.xUbuntu_12.04
> Error: Dependency is not satisfiable: libtinyxml2-2v5 (>= 2.0.2)

Is anyone else having this issue?
Thanks :)

**Comment by ablwr** [comment]
(AKA: I don't know but I know someone who might. ;))

**Comment by JeromeMartinez** [comment]
libzen: you must uninstall libzen-dev from your distro first because it is outdated, then install the updated libzen-dev from our website.

libmediainfo: we broke something when we changed our scripts for Ubuntu 15.10. working on that. In the meanwhile, you can test MediaConch 15.10 with libmediainfo 0.7.79 by replacing the version numbers in the download links.

**Comment by JeromeMartinez** [comment]
libzen: if you don't want to uninstall the -dev package, you can use the command line:
sudo dpkg -i libzen0_0.4.32-1* libzen-dev_0.4.32-1*
after having downloaded the 2 packages (the binary and the dev one)

libmediainfo as well as MediaConch: I updated the download pages with the previous stable version (libmediainfo 0.7.79 and MediaConch 15.10) which is working, except for Ubuntu 15.11 (the newest version are working well on Ubuntu 15.11).

**Comment by GuillaumeRoques** [comment]
The build have been fixed, you can download libmediainfo again.

**Comment by pjotrek-b** [comment]
Downloaded the deb-files (libzen, libmediainfo) again. Works now :)

1) Uninstalled "libzen-dev":
> $apt-get remove libzen-dev

2) Then installed libzen0, then libmediainfo0.
No problems this time.

3) This also fixes #86 :)
