### ISSUE TITLE
"Implementation report VALID": Error

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#85]
Clicking on the "eye" icon to view the report, returns a pop-up with an error message:
"Validation generated an internal error"

MediaConch v15.11 (Xubuntu Precise 12.04.3 LTS)

**Comment by pjotrek-b** [comment]
Same applies to "Policy report" :(

**Comment by ablwr** [comment]
Hi Peter. Any details to share about the video you were testing, or are you getting this with anything? Could be related to problems with the Ubuntu version of the build (I don't have this problem with the mac version).

**Comment by pjotrek-b** [comment]
I'm getting this with everything.
Also suspecting it to be a problem with that specific Ubuntu build, as I don't recall having this error on Windows7.

**Comment by ablwr** [comment]
Glad you are here filing issues. I'll also send these over to Jerome. Good morning, Jerome.

**Comment by pjotrek-b** [comment]
Seems to be caused by MediaInfoLib/LibZen not installed properly.
Issue is gone since fixing issue #84.
Therefore possibly a duplicate of #86.
