### ISSUE TITLE
Cosmetic: Narrow table space / padding?

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#89]
The formatting of the tables in the report looks very clinched:
![mediaconch-15 11-little_table_padding](https://cloud.githubusercontent.com/assets/2419195/11605878/7fd9bf7c-9b0b-11e5-96f2-8cedaef10aac.png)

I suppose it's related to one of these stylesheets?
https://github.com/MediaArea/MediaConch/tree/master/MetadataDevelopment/Displays/HTMLOutput

If so, then the commit messages indicate that is is work in progress already.
Then, nevermind.

**Comment by dericed** [comment]
Not a comment on this issue in particular. Just saying: Go @pjotrek-b !!!! MOAR issues!

**Comment by ablwr** [comment]
To comment on this issue in particular though, work on updating this is in progress!

**Comment by ablwr** [comment]
This should look extra stylish next release.

**Comment by ablwr** [comment]
HTML output needs work but this particular example was resolved, so closing this issue.
