### ISSUE TITLE
Wishlist: Remember previous options

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#90]
After running a check, it would be great if MediaConch GUI could remember the previously used settings and the recent folder/file that was selected.
When checking multiple files in a subfolder structure, it becomes annoying pretty quickly... :(

If MediaConch would remember that between restarts, it'd be even greater.
(v15.11)

**Comment by tribouille** [comment]
Not done, but with the Database introduction, it will take less time (Not analyse again and again)

**Comment by tribouille** [comment]
Done with the settings tab
