### ISSUE TITLE
No indicator/reminder if policy was edited but not saved

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#92]
When creating a new policy, one must press the "Save policy set" button in order not to lose changes during close/reopen of MediaConch.

When editing a policy, one cannot see whether the file was saved or not - or if changes are pending.

It might be nice to have:
1) some visual indicator if the file was written - or if changes are pending.
2) maybe a query window before closing the application if changes are pending.

Just an idea.

**Comment by dericed** [comment]
+1

**Comment by tribouille** [comment]
Hi,
in case you have a change pending for a policy, you should have a notification pop-up:
"
All policy changes not saved will be discarded?
Policies not saved:
$List_of_policies_with_changes
"
and three buttons:
OK | Save | Cancel

If you don't have it, can you give me your environment?
(I suppose it is xUbuntu 12.04)
Or maybe depending of your workflow?

Ok for the 1)

**Comment by pjotrek-b** [comment]
I now do get that notification pop-up (Xubuntu 12.04, MediaConch v15.11).
Maybe this was also related to issue #84?

Seems fine now!
Thanks :)
