### ISSUE TITLE
update install instructions

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaConch#95]
We should have one place to make the installation options clear. This should include installation via the pre-build installer files, building from source, and installing from homebrew. Installing from source can actually be deduced from the [homebrew recipe](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mediaconch.rb), but this should be written somewhere to response to the feedback about missing installation instructions.

**Comment by ablwr** [comment]
This is done and will be visible on the website on next deploy ("from source" is described in relevant repository, which could use expansion in the future). https://github.com/MediaArea/MediaConch-Website/blob/master/installation.md
