### ISSUE TITLE
Report text cut off if line too long

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#96]
I've just encountered the case where I can't read the full value in a report (e.g. MediaInfo):

![mediaconch-15 11-report_text_cutoff](https://cloud.githubusercontent.com/assets/2419195/11840575/31fe4cc4-a3f7-11e5-932f-c6275e1058ba.png)
See the value (blue highlight) being cut off after "subme=2 / ..."

The width of the report is limited to a fixed maximum width - and no horizontal scrollbars are shown.
Selecting the string and dragging the end outside of the canvas also doesn't scroll.

**Comment by GuillaumeRoques** [comment]
It's also fixed with https://github.com/MediaArea/MediaConch/issues/99
Column have no more predefined width size, they will scale automatically with the content (if content is too large there is an horizontal scrollbar)

**Comment by dericed** [comment]
will this work if the string contains line-breaks?

**Comment by GuillaumeRoques** [comment]
It should work but please test it if you have such a file.
