### ISSUE TITLE
Icon char in header not displayed correctly

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#97]
In the upper left corner of the application, you can see a "ð" character:
![mediaconch-15 11-report_text_cutoff](https://cloud.githubusercontent.com/assets/2419195/11840686/0bbc726a-a3f8-11e5-97ec-885b7ac72dc4.png)
I suppose that this should be rendered as a different symbol?

OS: Xubuntu 12.04.3 (64bit).
MediaConch: v15.11

**Comment by GuillaumeRoques** [comment]
I confirm that and it has been fixed yesterday :) ( https://github.com/MediaArea/MediaConch_SourceCode/commit/16a66d6bfca5700cc7371c5602cba01ee74d9bca )
You can test it if you want with our daily snapshots :
https://mediaarea.net/MediaConch/downloads/snapshots.html
Direct link for you environment : 
https://mediaarea.net/download/snapshots/binary/mediaconch-gui/20151216/mediaconch-gui_15.11.20151216-1_amd64.xUbuntu_12.04.deb

**Comment by pjotrek-b** [comment]
Will check.
Thanks for the convenience of providing the direct link ;)
