### ISSUE TITLE
Misleading wording: MediaInfo, MediaTrace

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#98]
Disclaimer: Yes, I'm picky ;)

I find the mixed-case wording for e.g. "MediaInfo" and "MediaTrace" in reports a bit misleading.
Especially when the report shows the button "Download MediaInfo" - since that sounds like I would then download the "MediaInfo" application.

Maybe it might be clearer to just name it "media info" and "media trace"?
Just an idea...

**Comment by JeromeMartinez** [comment]
> Disclaimer: Yes, I'm picky ;)

and we like it :), and we need more people doing same.
This is the goal of public discussion, and it is good to discuss about every issue.

> Maybe it might be clearer to just name it "media info" and "media trace"?

or "MediaInfo report" and "MediaTrace report"?

@dericed your thoughts?

**Comment by pjotrek-b** [comment]
Hm...
"MediaInfo report" and "MediaTrace report" seems clearer.

I guess the intention is, that it actually **is** the report of [MediaInfo](https://mediaarea.net/en/MediaInfo) and [MediaTrace](https://mediaarea.net/MediaTrace/)?

**Comment by pjotrek-b** [comment]
btw: It's an amazing feature to have MediaInfo/MediaTrace built-in to MediaConch.
Especially, because it already covers way more formats than just the PREFORMA target FFV1/PCM/MKV.

Great job guys! :smile:

**Comment by pjotrek-b** [comment]
Update:
What about just "Download report" - like in "Policy Report" and "Implementation Report"?
That'd be consistent and clear (in my opinion).

**Comment by JeromeMartinez** [comment]
> I guess the intention is, that it actually is the report of MediaInfo and MediaTrace?

Right, we integrate tools in order to have all in one place.

> btw: It's an amazing feature to have MediaInfo/MediaTrace built-in to MediaConch.

We appreciate that someone appreciates that :).

> What about just "Download report" - like in "Policy Report" and "Implementation Report"?

We plan to have some changes in the way we display (1 line only per file), we'll see at this moment how to have coherent and understandable names / tips.

**Comment by pjotrek-b** [comment]
Tested with daily build "16.09.20161030":
Thanks for renaming it to "MediaInfo report" and "MediaTrace report". 

No more confusion.
Considering this closed :tada: 
Thanksalot!
