### ISSUE TITLE
Column resize doesn't work in MediaTrace HTML report

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#99]
In the MediaTrace report HTML output, the resizing the column-width (Offset / Key / Value) doesn't work.

When moving the mouse over the column separator in the table header, the mouse cursor correctly changes to the left-right arrow.
However, when trying to resize (by dragging), only the text is selected instead.

Works fine in MediaInfo report HTML output.

**Comment by GuillaumeRoques** [comment]
The fix is here : https://github.com/GuillaumeRoques/MediaConch_SourceCode/commit/1da827a2ea1d953dd5fda09c97501574dbd7a9db and will be in the next release
